[package]
name = "ministry-of-fey-secrets"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
shuttle-axum = "0.35.0"
shuttle-runtime = "0.35.0"
shuttle-secrets = "0.35.0"
starknet = "0.8.0"
tokio = "1.28.2"
tracing = "0.1.40"
